/**
     * @file rtsyn/internal/rthybrid_komendantov_kononenko_1996_neuron.h
     * @brief Internal state for the RTHybrid Komendantov-Kononenko 1996 Neuron module.
     *
     * SPDX-License-Identifier: GPL-3.0-or-later
     */
    #ifndef RTSYN_INTERNAL_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_H
    #define RTSYN_INTERNAL_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_H

    #include <stddef.h>
    #include <stdint.h>

    #ifdef __cplusplus
    extern "C" {
    #endif

    typedef struct rtsyn_rthybrid_komendantov_kononenko_1996_neuron_instance_s {
        double vars[8];
double p[20];
double burst_duration;
double burst_duration_value;
double freq;
size_t s_points;
double input_syn;
double input_burst_duration;
    } rtsyn_rthybrid_komendantov_kononenko_1996_neuron_instance_t;

    typedef enum rtsyn_rthybrid_komendantov_kononenko_1996_neuron_instance_ports_e : uint32_t {
        RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PORT_ISYN_NA = 0,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PORT_BURST_DURATION_S = 1,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PORT_VM_V = 2,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PORT_VM_MV = 3,
        RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PORT_COUNT = 4,
    } rtsyn_rthybrid_komendantov_kononenko_1996_neuron_instance_ports_t;

    typedef enum rtsyn_rthybrid_komendantov_kononenko_1996_neuron_instance_params_e : uint32_t {
        RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_BURST_DURATION = 0,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_I = 1,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_CM = 2,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_G_NA_V = 3,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_V_NA = 4,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_G_NA = 5,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_G_NA_TTX = 6,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_G_K = 7,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_G_K_TEA = 8,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_V_K = 9,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_G_B = 10,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_V_B = 11,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_G_CA = 12,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_V_CA = 13,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_G_CA_CA = 14,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_K_BETA = 15,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_BETA = 16,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_RHO = 17,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_K_S = 18,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_V0_MV = 19,
        RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_PARAM_COUNT = 20,
    } rtsyn_rthybrid_komendantov_kononenko_1996_neuron_instance_params_t;

    typedef enum rtsyn_rthybrid_komendantov_kononenko_1996_neuron_instance_states_e : uint32_t {
        RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_STATE_M = 0,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_STATE_H = 1,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_STATE_N = 2,
RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_STATE_CA = 3,
        RTSYN_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_STATE_COUNT = 4,
    } rtsyn_rthybrid_komendantov_kononenko_1996_neuron_instance_states_t;

    #ifdef __cplusplus
    }
    #endif

    #endif /* RTSYN_INTERNAL_RTHYBRID_KOMENDANTOV_KONONENKO_1996_NEURON_H */
